config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/contact', to: 'pages#contact'
  get 'pages/about', to: 'pages#about'
  #get 'error', to: "pages#error"

  get 'blog', to: redirect("http://msn.com") 

  resources :projects do
    resources :tasks, except: [:index], controller: 'projects/tasks'
  end  
  
  root 'pages#home'
  #get '*path', to: redirect("/error")
end

app/models/counter.rb
class Counter

	def self.calculate_percent_complete(completed_tasks, total_tasks)
		completed_tasks.to_f / total_tasks.to_f * 100
	end
end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :tasks

	after_initialize :set_defaults

	validates_presence_of :title, :description, :percent_complete

	scope :almost_completed, -> { where('percent_complete > 75.0') }
	scope :still_needs_some_work, -> { where('percent_complete < 75.0') }

	def set_defaults
		self.percent_complete ||= 0.0
	end
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project

  after_save :update_percent_complete if :mark_completed?

  scope :completed, -> { where(completed: true) }

  #mount_uploader :task_file, TaskFileUploader

  def mark_completed?
  	self.completed == true
  end

  def update_percent_complete
  	project = Project.find(self.project_id)
  	count_of_completed_tasks = project.tasks.completed.count
    count_of_total_tasks = project.tasks.count
    project.update!(percent_complete: Counter.calculate_percent_complete(
      count_of_completed_tasks, count_of_total_tasks))
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
  def contact
  end

  def about
  	@title = "My Cool Page"
  end

  def home
  	@projects = Project.all.limit(10)
  end

  def error  	
  end
end

app/controllers/projects/tasks_controller.rb
class Projects::TasksController < ApplicationController

	before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :new, :edit, :create,:update, :destroy]

  def show
  end

  def new
  	@task = Task.new
  end

  def edit
  end

  def create
  	@task = Task.new(task_params)
    @task.project_id = @project.id
  
  	respond_to do |format|
  		if @task.save     # passes validations
  			format.html { redirect_to project_url(@task.project_id), 
  				notice: "Task was created successfully!" }
  			format.json { render :show, status: :created, location: @task }
  		else              # fails validations      
  			format.html { render :new }
  			format.json { render json: @task.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def update
  	respond_to do |format|
  		if @task.update(task_params)
  			format.html { redirect_to project_url(@task.project_id), 
  				notice: "Task was updated successfully!" }
  			format.json { render :show, status: :created, location: @task }
  		else
  			format.html { render :edit }
  			format.json { render json: @task.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def destroy
  	@task.destroy
		respond_to do |format|
			format.html { redirect_to project_url(@task.project_id), 
				notice: "Task was deleted successfully!" }
			format.json { head :no_content }
		end
  end

  private

  def set_task
  	@task = Task.find(params[:id])
  end

  def task_params
  	params.require(:task).permit(:title, :description, :project_id, :completed,
      :task_file)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  
  def index
    #@projects = Project.almost_completed 
    @projects = Project.all
  end

 
  def show
    @tasks = @project.tasks
  end

 
  def new
    @project = Project.new
  end

 
  def edit
  end

 
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    
    def set_project
      @project = Project.find(params[:id])
    end
   
    def project_params
      params.require(:project).permit(:title, :description, :percent_complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<%= link_to "Home", root_path %>
<%= link_to "About", pages_about_path %>
<%= link_to "Contact", pages_contact_path %>
<%= link_to "Blog", blog_path %>
<%= link_to "Projects", projects_path %>
<% if current_user %>
	<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
	<%= link_to "Edit Profile", edit_user_registration_path  %>
<% else %>
	<%= link_to "Sign In", new_user_session_path %>
	<%= link_to "Sign Up", new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= image_tag('logos/rails.png', size: '50x40') %>
	<br>
	<%= render 'layouts/navbar' %>
	<%= render 'layouts/alerts' %>

	<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/error.html.erb
<h1>Sorry, that page does not exist!</h1>

Go back to <%= link_to "homepage", root_path %>

app/views/pages/home.html.erb
<h1>Home Page</h1>

<div class="homepage-projects">
	<%= render 'projects/projects' %>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :percent_complete %><br>
    <%= f.text_field :percent_complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_projects.html.erb
<% @projects.each do |project| %>	
	<p><strong>
		<%= project.title %></strong> -
		<em><%= project.description %></em> ---
		<%= project.percent_complete %>
		<%= "*** #{project.percent_complete}" if !project.percent_complete %>
	</p>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Percent complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.percent_complete.to_f %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Percent complete:</strong>
  <%= @project.percent_complete %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

</br>

<hr>

<h4>Tasks for project</h4>

<% @tasks.each do |task| %>
	<p><%= link_to task.title, project_task_path(@project.id, task.id) %></p>
<% end %>

<%= link_to "Add a new Task for this project", new_project_task_path(project_id: @project.id)  %>

app/views/projects/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label "Attachment" %><br>
    <%= f.file_field :task_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/tasks/edit.html.erb
<%= render 'form' %>

app/views/projects/tasks/new.html.erb
<%= render 'form' %>

app/views/projects/tasks/show.html.erb
<hr>

<h2>Task:  <%= @task.title %></h2>

<p><strong>Desc:  </strong><%= @task.description %></p>

<h4>Task created at:  <%= @task.created_at.strftime("%m-%e-%y %H:%M") %></h4>

<% if @task.created_at != @task.updated_at %>
	<h4>Updated at:  <%= @task.updated_at.strftime("%m-%e-%y %H:%M") %></h4>
<% end %>

<% if @task.completed == true %>
	<h4><em>Task is completed</em></h4>
<% else %>
	<h4><em>Task is pending</em></h4>
<% end %>

<% if @task.task_file.blank? %>
	<p>No File "Attachment" is currently available</p>
<% else %>
	<p><%= link_to "Attachment", @task.task_file.to_s %></p>
<% end %>

<%= link_to "Edit", edit_project_task_path(@task.project_id, @task.id) %>

<%= link_to "Back", project_path(@task.project_id) %>